# 欢迎使用 Jekyll！
#
# 此配置文件用于设置影响整个博客的设置，这些值通常只需设置一次，之后很少需要编辑。
# 如果你发现自己经常编辑此文件，考虑使用 Jekyll 的数据文件功能来处理需要频繁更新的数据。
#
# 由于技术原因，当你使用 'bundle exec jekyll serve' 时，此文件不会自动重新加载。
# 如果你更改了此文件，请重启服务器进程。
#
# 如果你需要 YAML 语法方面的帮助，以下是一些快速参考：
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# 站点设置
# 这些设置用于个性化你的新站点。如果你查看 HTML 文件，
# 你会发现可以通过 {{ site.title }}、{{ site.email }} 等方式访问这些设置。
# 你可以创建任何自定义变量，它们可以在模板中通过 {{ site.myvariable }} 访问。

title: 野猫的小站
list_title: "最新文章"
email: game@freegamehub.top
description: >- # 这意味着忽略换行符，直到 "baseurl:"
  专注小游戏开发者变现实战，主介绍出海谷歌play，同时也涉及国内小游戏平台。欢迎关注，一起进步。
baseurl: "" # 站点的子路径，例如 /blog
url: "" # 站点的基本主机名和协议，例如 http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
#telegram_username: miaowurz
google_analytics: G-1RP6E6GC5H

# 构建设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 从处理中排除。
# 以下项目默认不会被处理。
# 此处 `exclude:` 键下列出的任何项目都会自动添加到
# 内部的 "默认列表" 中。
#
# 可以通过在 `include:` 列表中明确列出目录或
# 其条目的文件路径来处理被排除的项目。
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
